---
title: "Respiratory_Admissions"
author: "Merla Pumffrey"
date: "2024-03-19"
output:
  word_document: default
  html_document: default
---

```         
```

```         
```

```{r}

Bristol

In this section we are investigating the correlation between levels of pollutants and emergency Hospital Admissions relating to Respiratory Conditions in Children within Bristol.

#Link to the dataset
file_path <- "/Users/jordannelson/Documents/OneDrive - UWE Bristol Merla Pumffrey/Group Project/Data/Respiratory_Infection_data.xlsx"
df <- read_excel(file_path)

#Create subset of the data
df1 <- df[, c("Indicator_value", "NO2", "NO", "PM10","PM2_5")]
plot(df1)
```

```{r}
#Plot correlations
corrs <- cor(df1)
corrplot(corrs, method="number")
```

```{r}
#Investigate further the relationship between PM2.5 and Hospital admissions, as this is the only pollutant that has a correlation withe the admissions
with(df, cor(PM2_5,Indicator_value))
with(df, cor.test(PM2_5,Indicator_value))

# Scatter plot
library(ggplot2)
ggplot(df, aes(x=PM2_5, y=Indicator_value)) +
  geom_point() # + geom_smooth(method="lm")

```

```{r}
with(df, cor(PM2_5,Indicator_value))
with(df, cor.test(PM2_5,Indicator_value))

#find intercept, gradient and r-squared
model1 <- lm(PM2_5~Indicator_value, data=df)
summary(model1)
```

London Data

In this section we are investigating the correlation between levels of pollutants and emergency Hospital Admissions relating to Respiratory Conditions in Children within Bristol.

```{r}
df <- readxl::read_xlsx("/Users/danielhill/Documents/MSc Data Science/Interdisciplinary group project/Data/Air_quality_quarterly_london.xlsx", sheet = "Quarterly")

df2 <- readxl::read_xlsx("/Users/danielhill/Documents/MSc Data Science/Interdisciplinary group project/Data/London Respiratory hospital data.xlsx")
```

```{r}

df2 <- df2[, !colnames(df2) %in% c("Year", "Quarter", "Period of coverage")]

corrs <- cor(df2, use = "pairwise.complete.obs")
library(corrplot)
corrplot(corrs, method = "number")

model <- lm(`Indicator value` ~ NO2 + NO + PM10 + `PM2_5`, data = df2)
summary(model)
```
